### ISSUE TITLE
ansible - OSX run crash

### ISSUE THREAD

**Issue by imanassypov** [cisco-en-programmability/dnacenter_ansible_cli_templates#1]
when executing on OSX Monterey, getting following crash:

objc[13508]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[13508]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

ansible --version
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/Users/imanassy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/imanassy/.pyenv/versions/3.10.3/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/imanassy/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/imanassy/.pyenv/versions/3.10.3/bin/ansible
  python version = 3.10.3 (main, Mar 28 2022, 09:12:54) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.1
  libyaml = True

**Comment by jbogarin** [comment]
@imanassypov Check [this](https://github.com/cisco-en-programmability/dnacenter-ansible#attention-macos-users)

**Comment by imanassypov** [comment]
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

does the trick. Is there a more graceful way of dealing with this? Also not clear if this is a python ver dependency, or ansible?

**Comment by jbogarin** [comment]
It's actually a Mac Sierra thing that impacts Python and other programming languages that are using `fork()`. Here is more information about it. https://github.com/ansible/ansible/pull/31500
